#steps 1-6
#number1= input('Enter number 1')
#number2= input('Enter number 2')
#sum = int(number1) + int(number2)
#print(sum)
#difference= int(number1)-int(number2)
#multiplication= int(number1)*int(number2)
#division=int(number1)/int(number2)
#print(difference,multiplication,division)

number1= input('Enter number 1')
number2= input('Enter number 2')
number3= input('Enter number 3')
sum = int(number1) + int(number2) + int(number3)
difference= int(number1)-int(number2)-int(number3)
multiplication= int(number1)*int(number2)*int(number3)
division=(int(number1)/int(number2))/int(number3)
print(sum,difference,multiplication,division)
import math
#Return the value of 9 raised to the power of 3
print(math.pow(9, 3))
print(math.sqrt(64))
print (math.gcd(100, 20))
print(math.isinf(100))
print(math.fmod(600, 30))
print(math.fabs(-49.71))
print(math.ceil(16.35))
print(math.factorial(36))
print(math.exp(80))
print(math.gamma(-0.98))
print (math.cos(0.40))